Script started on 2021-09-14 16:45:00-06:00 [TERM="xterm-256color" TTY="/dev/pts/3" COLUMNS="113" LINES="23"]
]0;gabraham@gabraham-VirtualBox: ~/cse113/lab2/lab2/done[01;32mgabraham@gabraham-VirtualBox[00m:[01;34m~/cse113/lab2/lab2/done[00m$ ,[K./game
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: R
players move is ROCK
computers move is ROCK
Tie!
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: P
players move is PAPER
computers move is SPOCK
Player Wins!
Paper disproves Spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: S
players move is SCISSORS
computers move is PAPER
Player Wins!
Scissors cuts paper
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: ; L
players move is LIZARD
computers move is SCISSORS
Computer Wins!
Scissors decapitates lizard
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: V
players move is SPOCK
computers move is LIZARD
Computer Wins!
Lizard poisons Spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: R
players move is ROCK
computers move is SCISSORS
Player Wins!
Rock crushes scissors
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: r
unknown value try again.
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: error check
unknown value try again.
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: S V
players move is SPOCK
computers move is LIZARD
Computer Wins!
Lizard poisons Spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: Q S
players move is SCISSORS
computers move is ROCK
Computer Wins!
Rock crushes scissors
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: Q
]0;gabraham@gabraham-VirtualBox: ~/cse113/lab2/lab2/done[01;32mgabraham@gabraham-VirtualBox[00m:[01;34m~/cse113/lab2/lab2/done[00m$ exit
exit

Script done on 2021-09-14 16:45:53-06:00 [COMMAND_EXIT_CODE="0"]
