Script started on 2022-02-13 00:47:04-07:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="153" LINES="16"]
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ ./rock-spockgcc -g -Wall rock-spock.c -o rock-spock
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ gcc -g -Wall rock-spock.c -o rock-spock[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C./rock-spock[K
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: R
Player's play is ROCK
Computer's play is SPOCK
Computer Wins!
Spock vaporizes rock]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ ./rock-spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: P
Player's play is PAPER
Computer's play is LIZARD
Computer Wins!
Lizard eats paper
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ ./rock-spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: S
Player's play is SCISSORS
Computer's play is SPOCK
Computer Wins!
Spock smashes scissors
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ ./rock-spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: L
Player's play is LIZARD
Computer's play is PAPER
Player Wins!
Lizard eats paper
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ ./rock-spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: V
Player's play is SPOCK
Computer's play is SCISSORS
Player Wins!
Spock smashes scissors
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ ./rock-spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: Q
SPOCK eats a ROCK while chasing a LIZARD.
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ ./rock-spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: N
The value is unknown. Try again.
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ ./rock-spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: S
Player's play is SCISSORS
Computer's play is ROCK
Computer Wins!
Rock crushes scissors
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ ./rock-spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: L
Player's play is LIZARD
Computer's play is ROCK
Computer Wins!
Rock crushes lizard
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ ./rock-spock
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: V
Player's play is SPOCK
Computer's play is ROCK
Player Wins!
Spock vaporizes rock
]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ [K]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ [K]0;mad@CSE113: ~/Desktop/lab2/lab2[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab2/lab2[00m$ exit
exit

Script done on 2022-02-13 00:50:51-07:00 [COMMAND_EXIT_CODE="0"]
